name: 'Build Dockerfile + Push to GHCR'
author: 'marcusljx'
description: 'Basic building of Dockerfile and push to GitHub Container Repository'

inputs:
  docker-registry:
    description: 'docker registry to authenticate to'
    required: false
    default: ghcr.io
  docker-login:
    description: 'docker login username'
    required: false
    default: ${{ github.actor }}
  docker-password:
    description: 'docker login password'
    required: true

  file:
    description: 'Path to the Dockerfile. (default `{context}/Dockerfile`)'
    required: false
  push:
    description: 'Whether to actually push. Set to false for workflows where you only need to build but not push'
    required: false
    default: 'true'
  release-tag:
    description: 'release tag for the container (ie. after the `:`)'
    required: false
    default: latest
  build-args:
    description: 'build-args to pass to "docker build"'
    required: false
  labels:
    description: 'List of custom labels'
    required: false

outputs:
  tag:
    description: "Tag of the built container"
    value: ${{ inputs.docker-registry }}/${{ github.repository }}:${{ inputs.release-tag }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-login }}
        password: ${{ inputs.docker-password }}

    - id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.docker-registry }}/${{ github.repository }}
        labels: ${{ inputs.labels }}

    - uses: docker/build-push-action@v2
      with:
        file: ${{ inputs.file }}
        context: .
        push: ${{ inputs.push }}
        tags: ${{ inputs.docker-registry }}/${{ github.repository }}:${{ inputs.release-tag }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}