name: Test Workflow
on:
  push:
    branches:
      - main

env:
  CONTAINER_TAG: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    name: Run build-dockerfile-push Action
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build Dockerfile
        uses: marcusljx-actions/build-dockerfile-push@refs/heads/main
        with:
          file: ./test/Dockerfile
          tags: |
            ${{ env.CONTAINER_TAG }}

  test:
    needs:
      - build
    name: Pulling the built container and run it
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: read

    steps:
      - name: GitHub CR login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITHUB_CR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull container for GitHub CR
        run: docker pull ${{ env.CONTAINER_TAG }}

      - name: execute container
        run: docker run ${{ env.CONTAINER_TAG }}