name: Test Workflow
on:
  push:
    branches: ['main']

env:
  CONTAINER_REPO: ghcr.io
  CONTAINER_TAG: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    name: Run build-dockerfile-push Action
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build Dockerfile
        uses: marcusljx-actions/build-dockerfile-push@main
        with:
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          file: ./test/Dockerfile
          release-tag: latest

  test:
    needs:
      - build
    name: Pulling the built container and run it
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: read

    steps:
      - name: GitHub CR login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REPO }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull container for GitHub CR
        run: docker pull ${{ env.CONTAINER_TAG }}

      - name: execute container
        run: docker run ${{ env.CONTAINER_TAG }}