name: Test
on:
- push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    name: Test build-dockerfile-push Action
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build Dockerfile
        uses: marcusljx-actions/build-dockerfile-push@${{ env.COMMIT_SHA }}
        with:
          push: false